### ISSUE TITLE
Package unixodbc-dev has incorrect include 

### ISSUE THREAD

**Issue by Danack** [microsoft/linux-package-repositories#36]
**Describe the issue**

The package unixodbc-dev is trying to include the file "unixodbc.h" in version 2.3.11. That file does not exist in the package so it fails.

In version 2.3.7 the file of "unixodbc_conf.h" is part of the installed package and is used.

In version 2.3.11 the file of "unixodbc_conf.h" is part of the installed package but for some reason, the file "unixodbc.h" is referenced in sqltypes.h which is also part of the unixodbc-dev package.

Also, the file "unixodbc_conf.h" in 2.3.11 looks like it has been generated for a particular computer, compared to the file in 2.3.7 that looks like a generic source file ready to be compiled.

**When did the issue occur?**

The problem was first noticed yesterday, but if you're asking when the problem originated, it is somewhere between unixodbc-dev_2.3.7 and unixodbc-dev_2.3.11.

unixodbc-dev_2.3.7/usr/include/sqltypes.h:
```
#ifndef SIZEOF_LONG_INT
#include "unixodbc_conf.h"
#endif
```

unixodbc-dev_2.3.11/usr/include/sqltypes.h line 55-57:
```
#ifndef SIZEOF_LONG_INT
#include "unixodbc.h"
#endif
```

**If appplicable, what package did you attempt to install, and from which repo?**

Package is unixodbc-dev and appears to be installed from:

```
https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 unixodbc-dev amd64 2.3.11 [42.1 kB]
```

Debugging was done by manually downloading files from https://packages.microsoft.com/ubuntu/20.04/prod/pool/main/u/unixodbc/ and inspecting contents of files.

**Steps to Reproduce**
Short version, try to compile unixodbc into an application and [it will fail](https://github.com/php/php-src/actions/runs/4148457300/jobs/7176463762)

```
In file included from /usr/include/sql.h:19,
                 from /home/runner/work/php-src/php-src/ext/odbc/php_odbc_includes.h:107,
                 from /home/runner/work/php-src/php-src/ext/odbc/php_odbc.c:33:
/usr/include/sqltypes.h:56:[10](https://github.com/php/php-src/actions/runs/4148457300/jobs/7176463762#step:8:11): fatal error: unixodbc.h: No such file or directory
   56 | #include "unixodbc.h"
      |          ^~~~~~~~~~~~
compilation terminated.
```

I don't have a standalone test case.

**Actual Result**

Fails to find file as it is looking for the wrong file name.

**Expected Result**

Compilation succeeds

**Screenshots**

**Additional context**

This was noticed as part of [PHP's ci](https://github.com/php/php-src/actions/runs/4148457300/jobs/7176463762)

**Comment by AlexLinuxGallo91** [comment]
i have the same problem, when i install the package in my docker container (PHP-fpm 8.1) and enter to the path **/usr/include**, there's no the unixodbc.h in the listed files. 

![image](https://user-images.githubusercontent.com/59783026/218286704-2071976f-f9b2-49e7-831e-9efdabf2c789.png)

**Comment by bjverde** [comment]
I have the same problem, when i install the package in my docker container
the script works correctly until january 2023. Nothing has changed and now it has these issues

My DockerFile
https://github.com/bjverde/formDocker/blob/master/debian10_php8.1_mssql/debian10_apache_php81_mssql.Dockerfile

**Comment by bjverde** [comment]
In Debian 10, with php 8.1 changing the repository from Debian 10 to Debian 9. It will create the Docker script, I haven't tested if it will connect to the database, I believe so.

Change  
https://packages.microsoft.com/config/debian/10/prod.list
to 
https://packages.microsoft.com/config/debian/9/prod.list

**Comment by Korred** [comment]
Yeah, this hit us as well when trying to deploy a python application that uses `pyodbc`

**Comment by ylcdx** [comment]
With PHP 8.1 and Debian 11, changing the repository from 11 to 10 or from 11 to 9 does not fix the problem.  I still get the error :
`/usr/include/sqltypes.h:56:10: fatal error: unixodbc.h: No such file or directory`

**Comment by Yaroslav285** [comment]
Hello, 

Switching to the PHP image tag `8.1-apache-buster` and changing the repository to 9 helped me.

`https://packages.microsoft.com/config/debian/9/prod.list`


https://hub.docker.com/_/php/tags?page=1&name=8.1-apache-buster

**Comment by bogdanbradeanu** [comment]
i have the same problem. App built using 8.1.12-fpm-bullseye and i cannot replace this with something else.

**Comment by dbrmr** [comment]
I also have this problem when trying to install SQL Server drivers for PHP 8.2 on Debian 11

`sudo pecl install sqlsrv`

**Comment by jakeblatchford** [comment]
I'm currently working around this on `php:8.1-bullseye` by forcing installation of the old version:

```
apt-get install unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7
```

**Comment by ylcdx** [comment]
I confirm that Jack's solution works, thanks ;)

**Comment by lucasfcnunes** [comment]
> I'm currently working around this on `php:8.1-bullseye` by forcing installation of the old version:
> 
> ```
> apt-get install unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7
> ```

I had to run this on `python:3.7-slim-buster`:
```sh
apt-get installunixodbc-dev=2.3* unixodbc=2.3* odbcinst1debian2=2.3* odbcinst=2.3*
```

https://packages.debian.org/buster/unixodbc-dev 2.3.7 doesn't seem to exist on the official PPA...

**Comment by adiel91** [comment]
I can confirm the issue occurs for me as well, when using docker container based on debian11 distribution,
and trying to install pyodbc module for python2.
For python3 on same docker - no issues.

The WA that worked for me for now is similar to suggested above - install 2.3.7 versions explicitly:
`apt-get install unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7`

**Comment by cl-m-furkan** [comment]
Hit the same problem with pyodbc package (4.0.30) on python3.10.

>  For python3 on same docker - no issues.

Probably OK either because docker caches, or because using latest pyodbc version 4.0.35, which has binaries for x86_64_linux_glibc, so it skips compilation.. But the problem (broken include files) are still there.

Problem can still be reproduced by disabling binary downloads;

```
pip install --no-cache-dir --no-binary pyodbc --no-cache-dir pyodbc==4.0.35
```

Version pinning in `apt-get install` line helped our case as well, until this issue is fixed.

---

## How to check the cause

```
$ grep -nir -e 'unixodbc.*\.h' /usr/include/sqltypes.h
```

should NOT return a line like following;

```
#include "unixodbc.h"
```

because that file (unixodbc.h) is not packaged.

Correct result;

```
# grep -e unixodbc.*\.h /usr/include/sqltypes.h 
 * the install creates a unixodbc_conf.h file that contains the current build settings
#include "unixodbc_conf.h"
```

**Comment by yerlanamantaiuly** [comment]
**ubuntu 22.04** i confirm Jake's solution works too. 

RUN ACCEPT_EULA=Y apt-get install -y
msodbcsql17
mssql-tools
**unixodbc-dev=2.3.7
unixodbc=2.3.7
odbcinst1debian2=2.3.7
odbcinst=2.3.7**

RUN echo 'export PATH="$PATH:/opt/mssql-tools17/bin"' >> ~/.bashrc RUN exec bash
RUN pecl install **sqlsrv-5.8.0** RUN printf "; priority=20\nextension=sqlsrv.so\n" > /etc/php/7.3/mods-available/sqlsrv.ini

**Comment by David-Engel** [comment]
We are aware of the problem and are working on an updated 2.3.11 package for unixodbc-dev, ASAP.

Regards,
David

**Comment by cdillmann** [comment]
I could build with Debian 9.

curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
&& curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
&& apt-get -y update \
&& ACCEPT_EULA=Y apt-get install -y gnupg2 msodbcsql17 unixodbc-dev \

**Comment by akalinux** [comment]
I am having the same issue ia there a timeline for a fix?

**Comment by rodrigomartinezar** [comment]
> > I'm currently working around this on `php:8.1-bullseye` by forcing installation of the old version:
> > ```
> > apt-get install unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7
> > ```
> 
> I had to run this on `python:3.7-slim-buster`:
> 
> ```shell
> apt-get install unixodbc-dev=2.3* unixodbc=2.3* odbcinst1debian2=2.3* odbcinst=2.3*
> ```
> 
> https://packages.debian.org/buster/unixodbc-dev 2.3.7 doesn't seem to exist on the official PPA...

On `python:3.7.7-slim-buster` I had to run:
```shell
apt-get --allow-downgrades -y install unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7
```

**Comment by kndale** [comment]
This issue comes up when installing pdo_sqlsrv and sqlsrv PHP extensions on Ubuntu with PHP-FPM. Reproduced on 2 machines, making an upgrade to PHP8.1 not possible.

This documentation is currently not functional then:
https://learn.microsoft.com/en-us/sql/connect/php/installation-tutorial-linux-mac?view=sql-server-ver16

**Comment by sameervk** [comment]
Same issue here. The docker build was working fine using 'apt-get install unixodbc unixodbc-dev"  until today. Getting the same error 
![image](https://user-images.githubusercontent.com/16178000/219726950-1bb5c7e4-d059-4714-a6a4-6afbbb44b160.png)

**Comment by bobbrodie** [comment]
This probably isn't a **good** solution, but something that's working for us is to keep a copy of unixodbc.h from a version that was working, and copy it to where it's being looked for in the Docker build:

```
COPY ./docker/build/unixodbc.h /usr/include/unixodbc.h
```

I can't say I'd recommend this and YMMV, but it's something that's allowed us to keep the version of Ubuntu and MSSQL driver.

**Comment by SharkMachine** [comment]
> We are aware of the problem and are working on an updated 2.3.11 package for unixodbc-dev, ASAP.
> 
> Regards, David

If this was a problem in a Linux distro, it would've been fixed quite quickly. I'm quite disappointed Microsoft can't do that.

**Comment by SharkMachine** [comment]
@David-Engel the fact that my employer is paying for SQL Server and this is still not not fixed is not good.

**Comment by areed145** [comment]
Is there a timeline for this to be fixed? I am not able to implement any of the workarounds

**Comment by florentnestle** [comment]
Is there any plan to support Ubuntu 18.04 as well (especially in Az pipeline vm image) ?
Having to migrate to a newer version of Ubuntu to resolve this bug is a no go.

**Comment by guest-fl** [comment]
It is still failing in Az pipeline using vm image Ubuntu 18.04. Any plan to support that version as well (having to upgrade to new Ubuntu version in order to fix this bug is a nO go) ?

**Comment by osimic** [comment]
> This is still an issue in `python:3.10-buster` when installing `pyodbc==4.0.28`.
> 
> I tried this: `unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7`
> 
> with `https://packages.microsoft.com/config/debian/10/prod.list` (and 11) without success.
> 
> Exception is the same: `/usr/include/sqltypes.h:56:10: fatal error: unixodbc.h: No such file or directory`
> 
> When I downgrade to Debian 9 everything works as expected.

Update: works with `pyodbc==4.0.35` and `--allow-downgrades unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7`

**Comment by hughmcmaster** [comment]
Why has Microsoft started providing the unixodbc packages?

Why can't we use the packages provided by Ubuntu?

**Comment by osimic** [comment]
> > This is still an issue in `python:3.10-buster` when installing `pyodbc==4.0.28`.
> > I tried this: `unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7`
> > with `https://packages.microsoft.com/config/debian/10/prod.list` (and 11) without success.
> > Exception is the same: `/usr/include/sqltypes.h:56:10: fatal error: unixodbc.h: No such file or directory`
> > When I downgrade to Debian 9 everything works as expected.
> 
> Update: works with `pyodbc==4.0.35` and `--allow-downgrades unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7`

Update: works with `pyodbc==4.0.35`, Debian 10 and no downgrades

**Comment by jvitorinoj** [comment]
In ubuntu 20 the solution was downgraded to

`unixodbc-dev=2.3.6-0.1build1 unixodbc=2.3.6-0.1build1 odbcinst1debian2=2.3.6-0.1build1 odbcinst=2.3.6-0.1build1`

**Comment by mbearup** [comment]
Closing as the original issue (unixodbc.h) has been resolved.
For issues with libodbc1 vs libodbc2, refer to [this issue](https://github.com/microsoft/linux-package-repositories/issues/39).

**Comment by Yaroslav285** [comment]
Hello, I tried to use Ubuntu's MS repo in Debian 11 and it works.

https://packages.microsoft.com/config/ubuntu/22.04/prod.list

For Debian's repo, it generates an error

```#4 46.78 libtool: link: warning: library '/usr/lib/x86_64-linux-gnu/libodbc.la' was moved.
#4 46.79 grep: /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
#4 46.79 /bin/sed: can't read /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
#4 46.79 libtool: link: '/usr/lib/x86_64-linux-gnu/libltdl.la' is not a valid libtool archive
#4 46.79 make: *** [Makefile:249: sqlsrv.la] Error 1
#4 46.79 ERROR: `make' failed```

after running the command

`pecl install sqlsrv`

**Comment by kndale** [comment]
> Hello, I tried to use Ubuntu's MS repo in Debian 11 and it works.
> 
> https://packages.microsoft.com/config/ubuntu/22.04/prod.list
> 
> For Debian's repo, it generates an error
> 
> ```
> #4 46.79 grep: /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
> #4 46.79 /bin/sed: can't read /usr/lib/x86_64-linux-gnu/libltdl.la: No such file or directory
> #4 46.79 libtool: link: '/usr/lib/x86_64-linux-gnu/libltdl.la' is not a valid libtool archive
> #4 46.79 make: *** [Makefile:249: sqlsrv.la] Error 1
> #4 46.79 ERROR: `make' failed```
> 
> after running the command
> 
> `pecl install sqlsrv`
> ```

I am running into this error now on Ubuntu 22.04

**Comment by PROFeNoM** [comment]
> I'm currently working around this on `php:8.1-bullseye` by forcing installation of the old version:
> 
> ```
> apt-get install unixodbc-dev=2.3.7 unixodbc=2.3.7 odbcinst1debian2=2.3.7 odbcinst=2.3.7
> ```

Hi, 

I'm trying to install sqlsrv in a debian buster container that I'm building on a mac m1, but I can't use jake's solution since there are [no arm64 packages available for version 2.3.7](https://packages.microsoft.com/debian/11/prod/pool/main/u/unixodbc/) (even using debian 11), and therefore I run into this incorrect include error when doing `pecl install sqlsrv`.

Are there any actual workaround in this scenario?
